config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :articles

  root 'articles#index'

  

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true
	validates :text, presence: true
	validates :user_id, presence: true
	validates :medium, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index, :show]
	before_action :require_user, except: [:index, :show]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5).order('created_at DESC')
		respond_to do |format|
  			format.html
  			format.js
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def new	
	  @article = Article.new	
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user

		if @article.save
			flash[:success] = "Article successfully created"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
 
  		if @article.update(article_params)
  			flash[:success] = "Article successfully updated!"
    		redirect_to root_path
  		else
    		render 'edit'
  		end
	end

	def destroy
		@article = Article.find(params[:id])
  		@article.destroy
  		flash[:danger] = "The article was successfully deleted"
 
  		redirect_to root_path
	end

	private
		def article_params
				params.require(:article).permit(:title, :text, :medium)
		end

		 def require_user
    		authenticate_user!
  		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_article.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="well">
      
      <div class="row">
        <div class="col-xs-12">
          <div class="article article-title">
            <%= link_to article.title, article_path(article) %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <%= link_to "Read on Medium", "http://#{article.medium}", id: "medium_btn", class: "btn btn-xs btn-primary", target: "_blank" %>
        </div>
      </div>
      
      <div class="article-body">
        <%= truncate(strip_tags(article.text), length: 400) %>
      </div>
      <% if user_signed_in? && current_user == article.user %>
        <div class="article_actions">
          <%= link_to 'Edit', edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to 'Delete', article_path(article), method: :delete, 
                  data: { confirm: 'If you press "yes" you won\'t be able to undo this action' },
                  class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group"> 
        <div class="control-label">
          <% f.label :title %>
        </div>
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title here...", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group"> 
        <div class="control-label">
          <% f.label :medium %>
        </div>
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.text_field :medium, class: "form-control", placeholder: "Medium link here (without http://)...", autofocus: true %>
        </div>
      </div>

      <div class="form-group"> 
        <div class="control-label">
          <% f.label :text %>
        </div>
         <div class="col-sm-offset-2 col-sm-8">
        <%= f.text_area :text, rows: 20, class: "form-control", placeholder: "Write here...", autofocus: true %>
        </div> 
      </div>
      <div class="form-group"> 
        <div class="col-sm-offset-2 col-sm-4">
          <%= f.submit "Publish now", class: 'btn btn-primary btn-md' %>
          <%= link_to 'Cancel', root_path, class: 'btn btn-danger btn-md' %>        
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Editing article</h1>
 
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container-fluid">
  
  <div class="row">
    <div class="col-md-6">
      <div class="well">
        <div class="greeting">    
          <h1>THE 100 DAYS CHALLENGE<br />ABOUT USERS</h1>
          <p id="p_first">
            The 100 Days Challenge About Users is a self-challenge that I created to enhance my own UX and Web Design skills.
          </p>
          <p>
            My name is Roberto Pesce, I am a UX Designer and during 100 days I will be posting one article, every day, talking about my discoveries in UX.
          </p>
          <p>
            I'll be publishing the articles both here and on my Medium account, and will be curating relevant content and sharing it on Facebook.
          </p>
          <p id="p_last">
            Come along with me in this challenge! You can read the articles, follow the challenge on Facebook, follow me on Medium, and also use the hashtag #100DaysAboutUsers every time you share any UX content. <br />
            Let's spread UX and learn together!
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/7NHiyJ_GYss" allowfullscreen>
        </iframe>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="blue_bgd">
        <% init_date_time = DateTime.parse("2016-09-20 00:01:00") %> <!-- Initial date -->
        <% now_date_time = DateTime.now.to_date %> <!-- Today's date -->
        <% day_today = (now_date_time.to_date - init_date_time.to_date + 1).to_i %> <!-- Days gone so far -->
        <div>
          <p><span class="numbers">3 </span>Books read |<span class="numbers"> 3 </span>Influencers interviewed | <span class="numbers">404 </span>Articles read | <span class="numbers"><%= Article.count %> </span>Articles written</p>
        </div>
      
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="articles_list">
        <h2>ALL ARTICLES</h2>
        <div id="listing_articles">
          <%= render @articles %>
        </div>
      </div>
    </div>
  </div>
  
  <div align="center" id="infinite-scrolling">
    <%= will_paginate @articles %>
  </div>

</div>

app/views/articles/index.js.erb
$('#listing_articles').append('<%= j render @articles %>');
	<% if @articles.next_page %>
		$('.pagination').replaceWith('<%= j will_paginate @articles %>');
	<% else %>
		$(window).off('scroll');
		$('.pagination').remove();
	<% end %>

app/views/articles/new.html.erb
<h1 align="center">Publishing a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="show_h2" align="center"><%= @article.title %> </h2>
	<div class="well col-xs-12">
  		<%= simple_format(@article.text) %>
	</div>
  	<div class="col-xs-12">
	  	<div class="article_actions">
	  		<%= link_to 'Back', root_path, class: "btn btn-xs btn-success" %>
	  		<%= link_to "Read on Medium", "http://#{@article.medium}", id: "medium_btn", class: "btn btn-xs btn-primary", target: "_blank" %>

	  		<% if user_signed_in? %>
		  		<%= link_to 'Edit', edit_article_path(@article), class: "btn btn-xs btn-warning" %>
				<%= link_to 'Delete', article_path(@article), method: :delete, 
											data: { confirm: 'If you press "yes" you won\'t be able to undo this action' },
											class: "btn btn-xs btn-danger" %>
			<% end %>
		
		</div>
	</div>

app/views/layouts/_footer.html.erb
<footer>
 	<small>100 Days Challenge About Users &copy; 2016</small><br />
 	<small>Developed by: Roberto Pesce</small>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%= "#{name}" %>'>
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
	</div>
</div>	

app/views/layouts/_navigation.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">About the project and the author</h4>
      </div>
      <div class="modal-body">
        <h3>The challenge</h3>
        <p>The 100 Days Challenge About Users is a self-challenge developed by Roberto Pesce to enhance his UX design and web design skills, consisting in two moments: <br />

        Create the assets from scratch: <br />
        - About Users brand <br />
        - UX project <br />
        - Backend development <br />
        - Frontend development <br />
        
        <br />
        Do the following activities during 100 days in a row:<br />
        - Curate UX content<br />
        - Share relevant content on Facebook<br />
        - Post one article every day

        <h3>The author</h3>
        <p>Roberto Pesce is a brazilian UX Designer with background in business, project management and design. He lives in San Diego, California, and works as UX Designer freelancer, helping companies and entreperneurs on identifying and solving design problems.
        <br />
        <br /><a href="https://www.linkedin.com/in/roberto-pesce-jr-00746249" target="_blank">Check Roberto's LinkedIn profile</a>
        <br /><a href="https://www.behance.net/robertopesce" target="_blank">Check Roberto's online portfolio</a>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('main_logo.png', :class => "navbar-brand"), root_path %>
    </div>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Read on Medium", "https://www.medium.com/@robertopesce", target: "_blank" %></li>
        <li><%= link_to "Go to Facebook", "http://www.facebook.com/aboutusersux", target: "_blank" %></li>
        <li>
        <!-- Button trigger modal -->
        <a data-toggle="modal" data-target="#myModal" href="#">
          About
        </a>
        </li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span>
              <ul class="dropdown-menu">
                <li><%= link_to 'New article', new_article_path %></li>
                <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
              </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "About Users | UX Design | 100 Days Challenge | User Experience" %></title>
    
    <meta name="keywords" content="user experience, UX, design, user centered design, about users, technology" /> 
    <meta name="description" content="100 Days Challenge About Users is an UX project created to share the trends, tools, processes and best practices in user experience design." />
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-83911502-1', 'auto');
        ga('send', 'pageview');
    </script>
  </head>
  <body>
    <%= render 'layouts/navigation' %>

    <div class="container">     
        <div class="row">      
            <div class="col-lg-12">          
                <%= bootstrap_flash %>
                <%= yield %>
            </div>
        </div><!--/row-->
    </div> <!-- /container -->
    
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>